language: minimal

addons:
  apt:
    packages:
      - luarocks

git:
  depth: 150

install: luarocks install --local luacheck

script: /home/travis/.luarocks/bin/luacheck . --no-color -q

after_success:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash; if [[ $? != 0 ]]; then TRAVIS_TEST_RESULT=1; fi
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.2 -w 24947; if [[ $? != 0 ]]; then TRAVIS_TEST_RESULT=1; fi
notifications:
  email:
    on_failure: always
    on_success: never
